version: '3'

services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: versionControl_web
    command: > 
      bash -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../project:/src
    ports:
      - "8000:8000"
