# Generated by Django 2.2.5 on 2019-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='repositorie',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='tag',
        ),
        migrations.AddField(
            model_name='environment',
            name='tags',
            field=models.ManyToManyField(to='version_control.Tag'),
        ),
    ]
